In [1]:

import json
from datetime import datetime
import uuid
import time
import pandas as pd
import zipfile

#READ COORDINATES
zf = zipfile.ZipFile('./data/jakarta/data_jakarta_service_alpha.csv.zip') 
coordinates = pd.read_csv(zf.open('data_jakarta_service_alpha.csv'))

In [2]:
coordinates

        bus_code trip_id         gps_datetime   longitude  latitude    color
0       DMR 5049   5.112  2019-11-26 14:00:29  106.867523 -6.224230  #F2BA49
1       DMR 5049   5.112  2019-11-26 14:00:54  106.867523 -6.224230  #F2BA49
2       DMR 5049   5.112  2019-11-26 14:01:29  106.867523 -6.224230  #F2BA49
3       DMR 5049   5.112  2019-11-26 14:01:59  106.867523 -6.224230  #F2BA49
4       DMR 5049   5.112  2019-11-26 14:02:29  106.867523 -6.224230  #F2BA49
...          ...     ...                  ...         ...       ...      ...
775453   TSW 100  8.D001  2019-11-26 17:57:56  106.741697 -6.220093  #FF6600
775454   TSW 100  8.D001  2019-11-26 17:58:26  106.741697 -6.220093  #FF6600
775455   TSW 100  8.D001  2019-11-26 17:58:53  106.741697 -6.220093  #FF6600
775456   TSW 100  8.D001  2019-11-26 17:59:25  106.741655 -6.220058  #FF6600
775457   TSW 100  8.D001  2019-11-26 17:59:57  106.741638 -6.220033  #FF6600

[775458 rows x 6 columns]

In [12]:
coordinates.iloc[0]['gps_datetime']

'2019-11-26 14:00:29'